# creatate persistent volume claim
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jupyter-restore-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
# ---
apiVersion: batch/v1
kind: Job
metadata:
  name: jupyter-volume-restore
spec:
  template:
    spec:
      containers:
        - name: git-client
          image: alpine/git
          env:
            - name: GIT_AUTHOR_NAME
              valueFrom:
                secretKeyRef:
                  name: github-credentials-backup
                  key: GIT_AUTHOR_NAME
            - name: GIT_AUTHOR_EMAIL
              valueFrom:
                secretKeyRef:
                  name: github-credentials-backup
                  key: GIT_AUTHOR_EMAIL
            - name: GITHUB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: github-credentials-backup
                  key: username
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-credentials-backup
                  key: token
            - name: GITHUB_REPO_NAME
              valueFrom:
                secretKeyRef:
                  name: github-credentials-backup
                  key: GITHUB_REPO_NAME
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              CURRENT_DATE=$(date "+%Y-%m-%d_%H-%M-%S")
              git config --global user.name ${GIT_AUTHOR_NAME}
              git config --global user.email ${GIT_AUTHOR_EMAIL}
              git clone https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/${GITHUB_REPO_NAME}.git
              cd ${GITHUB_REPO_NAME}
              git checkout 2023-07-31_08-59-41 # Checkout the specific branch
              tar czf ${CURRENT_DATE}.tar.gz *
              mkdir -p /data
              mv ${CURRENT_DATE}.tar.gz /data/
          volumeMounts:
            - name: backup-restored-notebooks
              mountPath: /data
      restartPolicy: Never
      volumes:
        - name: backup-restored-notebooks
          persistentVolumeClaim:
            claimName: jupyter-restore-pvc # Replace with your actual PersistentVolumeClaim (PVC) name
