apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "filebeat-ingest.labels" . | nindent 4 }}
spec:
  type: filebeat
  version: {{ .Values.version }}
  elasticsearchRef:
    name: {{ .Values.elasticsearchRef }}
  configRef:
    secretName: {{ include "filebeat-ingest.fullname" . }}-config
  deployment:
    replicas: {{ .Values.replicaCount }}
    podTemplate:
      spec:
        {{- if .Values.nodePlacement.enabled }}
        nodeName: {{ .Values.nodePlacement.node }}
        {{- end }}
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: false
        securityContext:
          runAsUser: 0
        containers:
        - name: filebeat
          ports:
            - name: tcp
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

