apiVersion: v1
kind: Secret
metadata:
  name: {{ include "filebeat-ingest.fullname" . }}-config
  labels:
    {{- include "filebeat-ingest.labels" . | nindent 4 }}
stringData:
  beat.yml: |-
    filebeat.inputs:
    - type: tcp
      max_message_size: 10MiB
      host: "0.0.0.0:9514"
    output.kafka:
      hosts: {{ .Values.kafka.hosts }}
      topic: {{ .Values.kafka.topic }}
      max_message_bytes: 1000000
    output.elasticsearch.enabled: false
