apiVersion: v1
kind: Service
metadata:
  name: {{ include "filebeat-ingest.fullname" . }}
  labels:
    {{- include "filebeat-ingest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    common.k8s.elastic.co/type: beat
    beat.k8s.elastic.co/name: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 514
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      name: tcp